### ISSUE TITLE
簡繁轉換問題

### ISSUE THREAD

**Issue by puffdad** [project-trans/transfeminine-science#18]
我在台灣正體的多個頁面上看到『面板』一詞，切換至香港繁體為『皮膚』，切換至大陆简体為『皮肤』。

台灣正體適合的用詞亦為『皮膚』，猜測簡繁轉換時有問題，請協助修正，謝謝。

**Comment by saeziae** [comment]
確實爲已知的 OpenCC bug.

**Comment by Bersella-AI** [comment]
本人經過兩日試驗，已成功引入新版 OpenCC。
先介紹問題緣由：在實裝網站所用 GitHub Actions 腳本中，需引入 OpenCC 以轉換簡體中文原稿；但是腳本可用之 Ubuntu 最新環境爲 22.04 LTS 版本，**其中 OpenCC 版本爲 1.1.3**，早於此轉換問題修復之時間；如不更改腳本，須等待 GitHub 引入 Ubuntu 24.04 方可修復此問題。

昨日嘗試從 Docker 引入最新 OpenCC（1.1.7），無果，遂回退。

今日得知 Alpine Linux 可獲取最新版 OpenCC，在私人伺服器試驗後更新腳本，成功，運行過程可參見[此處](https://github.com/project-trans/transfeminine-science/actions/runs/7045156674/job/19174298508)。私人伺服器和遠端網頁的轉換結果一致。歡迎自行驗證。

如無異議，本 issue 將於 72 小時後關閉。:heart:
